apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  volumes:
  - name: nginx-storage
    persistentVolumeClaim:
      claimName: nginx-pvc
  containers:
  - name: nginx
    image: nginx:latest
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: nginx-storage
    ports:
    - containerPort: 80