apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: deploy-nginx
  name: deploy-nginx
spec:
  replicas: 3
  selector:
    matchLabels:  
      app: deploy-nginx
  strategy: {}
  template:
    metadata:
      labels:
        app: deploy-nginx
    spec:
      containers:
      - image: anupdangi69/hello-app:latest
        name: hello-app
        ports:
        - containerPort: 3000

